name: Build & Test

on:
  push:
    branches: ['*']
  pull_request:
    branches: [master]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: self-hosted
    container:
        image: quantconnect/lean:foundation
        options: --cpus 12 --memory 12g
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run build and tests
        run: |
          # Build Data Source
          dotnet build ./QuantConnect.DataSource.csproj /p:Configuration=Release /v:quiet /p:WarningLevel=1 && \
          # Build Tests
          dotnet build ./tests/Tests.csproj /p:Configuration=Release /v:quiet /p:WarningLevel=1 && \
          # Run Tests
          dotnet test ./tests/bin/Release/net10.0/Tests.dll && \
          # Build Data Processing
          dotnet build ./DataProcessing/DataProcessing.csproj /p:Configuration=Release /v:quiet /p:WarningLevel=1

